// <auto-generated />
namespace Infrastructure.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class duong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(duong));
        
        string IMigrationMetadata.Id
        {
            get { return "201807180649316_duong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
