// <auto-generated />
namespace Infrastructure.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class duong1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(duong1));
        
        string IMigrationMetadata.Id
        {
            get { return "201807230900241_duong1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
